version: '3.8'

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER:
      POSTGRES_DB:
    volumes:
      - /var/lib/postgresql/data/